# Generated by Django 5.1.6 on 2025-08-10 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(max_length=32)),
                ('time_limit', models.IntegerField()),
                ('challenge_type', models.CharField(choices=[('coding', 'coding'), ('system_design', 'system_design'), ('algorithm', 'algorithm'), ('debugging', 'debugging'), ('architecture', 'architecture')], max_length=32)),
                ('challenge_question', models.TextField()),
                ('max_score', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('level', models.IntegerField(default=50)),
                ('validated', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='HireMe.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('experience_level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('lead', 'Tech Lead'), ('principal', 'Principal')], default='junior', max_length=32)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('open_to_offers', 'Open to Offers'), ('not_available', 'Not Available')], default='available', max_length=32)),
                ('resume', models.TextField(blank=True, null=True)),
                ('dev_score', models.IntegerField(default=0)),
                ('validation_status', models.CharField(default='not_validated', max_length=32)),
                ('portfolio_links', models.JSONField(blank=True, null=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='developers', to='HireMe.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_analysis', models.TextField()),
                ('answer', models.TextField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('accuracy_rate', models.FloatField(blank=True, null=True)),
                ('bugs_found', models.IntegerField(blank=True, null=True)),
                ('bugs_missed', models.IntegerField(blank=True, null=True)),
                ('false_positives', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('evaluating', 'evaluating'), ('completed', 'completed')], default='pending', max_length=16)),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('evaluation_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HireMe.challenge')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HireMe.developer')),
            ],
        ),
    ]
