# Generated by Django 5.1.6 on 2025-08-10 09:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HireMe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('required_level', models.IntegerField(default=70)),
            ],
            options={
                'unique_together': {('name', 'required_level')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('matching', 'Matching'), ('challenging', 'Challenging'), ('closed', 'Closed')], default='draft', max_length=32)),
                ('automation_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_count', models.IntegerField(default=0)),
                ('required_skills', models.ManyToManyField(blank=True, related_name='projects', to='Recruiter.projectskill')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('completed', 'Completed')], default='sent', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HireMe.challenge')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='HireMe.developer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='Recruiter.project')),
            ],
            options={
                'unique_together': {('project', 'developer')},
            },
        ),
        migrations.CreateModel(
            name='CandidateRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_score', models.FloatField(default=0.0)),
                ('rationale', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for', to='HireMe.developer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='Recruiter.project')),
            ],
            options={
                'unique_together': {('project', 'developer')},
            },
        ),
    ]
